u'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"\n  "http://www.w3.org/TR/html4/loose.dtd">\n<html>\n  <head>\n    <title>TypeError: \'NoneType\' object has no attribute \'__getitem__\' // Werkzeug Debugger</title>\n    <link rel="stylesheet" href="?__debugger__=yes&amp;cmd=resource&amp;f=style.css" type="text/css">\n    <!-- We need to make sure this has a favicon so that the debugger does not by\n         accident trigger a request to /favicon.ico which might change the application\n         state. -->\n    <link rel="shortcut icon" href="?__debugger__=yes&amp;cmd=resource&amp;f=console.png">\n    <script type="text/javascript" src="?__debugger__=yes&amp;cmd=resource&amp;f=jquery.js"></script>\n    <script type="text/javascript" src="?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js"></script>\n    <script type="text/javascript">\n      var TRACEBACK = 50161616,\n          CONSOLE_MODE = false,\n          EVALEX = true,\n          SECRET = "qGLqdty4Lt4hvi96rjiR";\n    </script>\n  </head>\n  <body>\n    <div class="debugger">\n<h1>TypeError</h1>\n<div class="detail">\n  <p class="errormsg">TypeError: \'NoneType\' object has no attribute \'__getitem__\'</p>\n</div>\n<h2 class="traceback">Traceback <em>(most recent call last)</em></h2>\n<div class="traceback">\n  \n  <ul><li><div class="frame" id="frame-50162320">\n  <h4>File <cite class="filename">"/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask/app.py"</cite>,\n      line <em class="line">1836</em>,\n      in <code class="function">__call__</code></h4>\n  <pre>return self.wsgi_app(environ, start_response)</pre>\n</div>\n\n<li><div class="frame" id="frame-50161744">\n  <h4>File <cite class="filename">"/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask/app.py"</cite>,\n      line <em class="line">1820</em>,\n      in <code class="function">wsgi_app</code></h4>\n  <pre>response = self.make_response(self.handle_exception(e))</pre>\n</div>\n\n<li><div class="frame" id="frame-50162064">\n  <h4>File <cite class="filename">"/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask_restful/__init__.py"</cite>,\n      line <em class="line">265</em>,\n      in <code class="function">error_router</code></h4>\n  <pre>return original_handler(e)</pre>\n</div>\n\n<li><div class="frame" id="frame-50161424">\n  <h4>File <cite class="filename">"/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask/app.py"</cite>,\n      line <em class="line">1403</em>,\n      in <code class="function">handle_exception</code></h4>\n  <pre>reraise(exc_type, exc_value, tb)</pre>\n</div>\n\n<li><div class="frame" id="frame-50161296">\n  <h4>File <cite class="filename">"/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask_restful/__init__.py"</cite>,\n      line <em class="line">262</em>,\n      in <code class="function">error_router</code></h4>\n  <pre>return self.handle_error(e)</pre>\n</div>\n\n<li><div class="frame" id="frame-50161936">\n  <h4>File <cite class="filename">"/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask/app.py"</cite>,\n      line <em class="line">1817</em>,\n      in <code class="function">wsgi_app</code></h4>\n  <pre>response = self.full_dispatch_request()</pre>\n</div>\n\n<li><div class="frame" id="frame-50162192">\n  <h4>File <cite class="filename">"/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask/app.py"</cite>,\n      line <em class="line">1477</em>,\n      in <code class="function">full_dispatch_request</code></h4>\n  <pre>rv = self.handle_user_exception(e)</pre>\n</div>\n\n<li><div class="frame" id="frame-50162256">\n  <h4>File <cite class="filename">"/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask_restful/__init__.py"</cite>,\n      line <em class="line">265</em>,\n      in <code class="function">error_router</code></h4>\n  <pre>return original_handler(e)</pre>\n</div>\n\n<li><div class="frame" id="frame-50162384">\n  <h4>File <cite class="filename">"/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask/app.py"</cite>,\n      line <em class="line">1381</em>,\n      in <code class="function">handle_user_exception</code></h4>\n  <pre>reraise(exc_type, exc_value, tb)</pre>\n</div>\n\n<li><div class="frame" id="frame-50161808">\n  <h4>File <cite class="filename">"/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask_restful/__init__.py"</cite>,\n      line <em class="line">262</em>,\n      in <code class="function">error_router</code></h4>\n  <pre>return self.handle_error(e)</pre>\n</div>\n\n<li><div class="frame" id="frame-50162512">\n  <h4>File <cite class="filename">"/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask/app.py"</cite>,\n      line <em class="line">1475</em>,\n      in <code class="function">full_dispatch_request</code></h4>\n  <pre>rv = self.dispatch_request()</pre>\n</div>\n\n<li><div class="frame" id="frame-50159952">\n  <h4>File <cite class="filename">"/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask/app.py"</cite>,\n      line <em class="line">1461</em>,\n      in <code class="function">dispatch_request</code></h4>\n  <pre>return self.view_functions[rule.endpoint](**req.view_args)</pre>\n</div>\n\n<li><div class="frame" id="frame-50162576">\n  <h4>File <cite class="filename">"/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask_restful/__init__.py"</cite>,\n      line <em class="line">446</em>,\n      in <code class="function">wrapper</code></h4>\n  <pre>resp = resource(*args, **kwargs)</pre>\n</div>\n\n<li><div class="frame" id="frame-50162640">\n  <h4>File <cite class="filename">"/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask/views.py"</cite>,\n      line <em class="line">84</em>,\n      in <code class="function">view</code></h4>\n  <pre>return self.dispatch_request(*args, **kwargs)</pre>\n</div>\n\n<li><div class="frame" id="frame-50162000">\n  <h4>File <cite class="filename">"/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask_restful/__init__.py"</cite>,\n      line <em class="line">550</em>,\n      in <code class="function">dispatch_request</code></h4>\n  <pre>resp = meth(*args, **kwargs)</pre>\n</div>\n\n<li><div class="frame" id="frame-50162704">\n  <h4>File <cite class="filename">"/home/achu/hoistme1.0/app/posts/views.py"</cite>,\n      line <em class="line">28</em>,\n      in <code class="function">post</code></h4>\n  <pre>data=json[\'text\']</pre>\n</div>\n</ul>\n  <blockquote>TypeError: \'NoneType\' object has no attribute \'__getitem__\'</blockquote>\n</div>\n\n<div class="plain">\n  <form action="/?__debugger__=yes&amp;cmd=paste" method="post">\n    <p>\n      <input type="hidden" name="language" value="pytb">\n      This is the Copy/Paste friendly version of the traceback.  <span\n      class="pastemessage">You can also paste this traceback into\n      a <a href="https://gist.github.com/">gist</a>:\n      <input type="submit" value="create paste"></span>\n    </p>\n    <textarea cols="50" rows="10" name="code" readonly>Traceback (most recent call last):\n  File "/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__\n    return self.wsgi_app(environ, start_response)\n  File "/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app\n    response = self.make_response(self.handle_exception(e))\n  File "/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 265, in error_router\n    return original_handler(e)\n  File "/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception\n    reraise(exc_type, exc_value, tb)\n  File "/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 262, in error_router\n    return self.handle_error(e)\n  File "/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app\n    response = self.full_dispatch_request()\n  File "/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File "/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 265, in error_router\n    return original_handler(e)\n  File "/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File "/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 262, in error_router\n    return self.handle_error(e)\n  File "/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File "/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 446, in wrapper\n    resp = resource(*args, **kwargs)\n  File "/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask/views.py", line 84, in view\n    return self.dispatch_request(*args, **kwargs)\n  File "/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 550, in dispatch_request\n    resp = meth(*args, **kwargs)\n  File "/home/achu/hoistme1.0/app/posts/views.py", line 28, in post\n    data=json[\'text\']\nTypeError: \'NoneType\' object has no attribute \'__getitem__\'</textarea>\n  </form>\n</div>\n<div class="explanation">\n  The debugger caught an exception in your WSGI application.  You can now\n  look at the traceback which led to the error.  <span class="nojavascript">\n  If you enable JavaScript you can also use additional features such as code\n  execution (if the evalex feature is enabled), automatic pasting of the\n  exceptions and much more.</span>\n</div>\n      <div class="footer">\n        Brought to you by <strong class="arthur">DON\'T PANIC</strong>, your\n        friendly Werkzeug powered traceback interpreter.\n      </div>\n    </div>\n  </body>\n</html>\n\n<!--\n\nTraceback (most recent call last):\n  File "/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__\n    return self.wsgi_app(environ, start_response)\n  File "/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app\n    response = self.make_response(self.handle_exception(e))\n  File "/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 265, in error_router\n    return original_handler(e)\n  File "/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception\n    reraise(exc_type, exc_value, tb)\n  File "/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 262, in error_router\n    return self.handle_error(e)\n  File "/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app\n    response = self.full_dispatch_request()\n  File "/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File "/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 265, in error_router\n    return original_handler(e)\n  File "/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File "/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 262, in error_router\n    return self.handle_error(e)\n  File "/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File "/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 446, in wrapper\n    resp = resource(*args, **kwargs)\n  File "/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask/views.py", line 84, in view\n    return self.dispatch_request(*args, **kwargs)\n  File "/home/achu/hoistme1.0/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 550, in dispatch_request\n    resp = meth(*args, **kwargs)\n  File "/home/achu/hoistme1.0/app/posts/views.py", line 28, in post\n    data=json[\'text\']\nTypeError: \'NoneType\' object has no attribute \'__getitem__\'\n\n-->\n'

